import sys
from antlr4 import FileStream, CommonTokenStream, ParseTreeWalker
from IndentLexer import IndentLexer
from minipythonParser import minipythonParser
from minipythonListener import minipythonListener

def main():
    # Run python file. Use the parser and lexer generated by ANTLR to parse a sample Python file.

    # Check for input file argument
    if len(sys.argv) < 2:
        print("Usage: python main.py <input_file>")
        sys.exit(1)

    input_file = sys.argv[1]
    print(f"Parsing file: {input_file}")

    # create input stream -> lexer -> token stream -> parser
    input_stream = FileStream(input_file)
    lexer = IndentLexer(input_stream)
    tokens = CommonTokenStream(lexer)
    parser = minipythonParser(tokens)

    # parse the input file starting from the 'prog' rule
    tree = parser.prog()

    # walk the parse tree and print the nodes
    walker = ParseTreeWalker()
    printer = minipythonListener()
    walker.walk(printer, tree)


if __name__ == '__main__':
    main()