

import sys
from antlr4 import FileStream, CommonTokenStream, ParseTreeWalker
from antlr4.tree.Trees import Trees

from .IndentLexer import IndentLexer
from .MyListener import MyListener

from generated.minipythonParser import minipythonParser
from generated.minipythonListener import minipythonListener

def main():
    # Run python file. Use the parser and lexer generated by ANTLR to parse a sample Python file.

    # Check for input file argument
    if len(sys.argv) < 2:
        print("Usage: python main.py <input_file>")
        sys.exit(1)

    input_file = sys.argv[1]
    print(f"Parsing file: {input_file}")

    # create input stream -> lexer -> token stream -> parser
    input_stream = FileStream(input_file)
    lexer = IndentLexer(input_stream)
    tokens = CommonTokenStream(lexer)
    parser = minipythonParser(tokens)

    # parse the input file starting from the 'prog' rule
    tree = parser.prog()

    # print the parse tree in a LISP-style format
    print("-------------------------------------------------------------------------")
    print("[TREE] (Lisp Style)")
    try:
        tree_str = Trees.toStringTree(tree, None, parser)
        print(tree_str)
    except (TypeError, AttributeError) as e:
        print(f"Error generating tree: {e}")
        print("Tree has None nodes - likely a parsing issue with if statements")
        
        # Let's check if there were syntax errors
        if parser.getNumberOfSyntaxErrors() > 0:
            print(f"Number of syntax errors: {parser.getNumberOfSyntaxErrors()}")
    print("------------------------------------------------------------------------")

    # create a listener
    listener = MyListener()

    # walk the parse tree and print the nodes
    walker = ParseTreeWalker()
    walker.walk(listener, tree)


if __name__ == '__main__':
    main()